name: Cypress Tests with Video Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --browser chrome

      - name: Upload Cypress Videos
        if: always()   # <-- Always run even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
