name: Cypress Tests with Video Upload

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm install
      
      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: npm run cy:run --browser chrome
        env:
          CYPRESS_baseUrl:  ${{ secrets.BASE_URL }}
          CYPRESS_username: ${{ secrets.USERNAME }}
          CYPRESS_password: ${{ secrets.PASSWORD }}

      - name: Upload Cypress Videos
        if: always()   # <-- Always run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: cypress/videos


      - name: Run Cypress Test
        run: npx cypress run --spec "cypress/e2e/demo.cy.js"
